# Generated by Django 5.1.1 on 2024-09-19 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_onetimepassword'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
